### ISSUE TITLE
Showcase how to create an up-to-date pending changelog

### ISSUE THREAD

**Issue by pat-s** [thegeeklab/git-sv#119]
Not a request, just some thoughts (that could potentially be a nice addition to the README):

`git sv release-notes` creates the currently pending changelog for the next upcoming version.

In the current CI runs of this repo there is already a step that generates those (https://github.com/thegeeklab/git-sv/blob/647aa9cf538545142d7877c5af9015f663947063/.woodpecker/build-package.yml#L20-L25) but only publishes them on a `tag` event.

Arguably, a pending changelog that is somewhat visible and easy to find while at the same time unintrusive can be beneficial for certain projects. I was thinking about this coming from the `plugin-release-ready-go` plugin. I like that `git-sv` is a lot more lightweight and doesn't keep a static PR that even triggers all `pull_request` workflows by default.

A middle-way between a static PR and local invocation could be to have a dedicated *pipeline* (instead of a step) that just `cat`s the pending release notes. 
I don't see an easy way to dynamically infer the link to the respective latest pipeline execution (to add this then to the README), so the README would likely need a statement like "for the pending changelog, visit the "changelog" pipeline of the most recent CI run of the main branch").

PS: very nice work overall! 👍️

**Comment by xoxys** [comment]
Personally, I would use an issue e.g. something like the renovate dashboard to always show the upcoming release changelog but I dont think I would like to implement it for this repo.

**Comment by pat-s** [comment]
An issue would be neat indeed. I also thought about this but had the impression that this tool wants to avoid forge-specific code/actions and aims to only interact with the local git information. Which is why I focused on the "link to the latest CI run" idea.

But yes, I also think that this would be great. It would also solve the issue of the `plugin-ready-release` plugin which always triggers unrelated checks for every changelog update.

**Comment by xoxys** [comment]
I don't want to implement it in this repo as, indeed, the tool should stay independent of a forge. My suggestion would to use preferred CI system to update a forge issue on every commit to the default branch.

**Comment by xoxys** [comment]
I'm going to close this issue for now. If you have built something like that and want to document it, I'm happy to add it to the readme. Hope that's fine for you.

**Comment by pat-s** [comment]
[Here's an example](https://git.devxy.io/helm/shinyproxy/src/commit/5b3260540395c16ea9421199fac895af98507144/.woodpecker/changelog.yaml) of a generic solution that can be c/p in any (Forgejo/Gitea) repo. It is also CI agnostic, thanks to `git-sv`, of course.

A similar solution can easily be created for GH, maybe you're motivated to do so?

Examples for both GH and Gitea in the README would be a great addition, I think.

**Comment by pat-s** [comment]
Forgot that the repo was private and is meanwhile deleted. Here's the example in text:

```yaml
clone:
  git:
    image: docker.io/thegeeklab/wp-git-clone:latest

when:
  event: [push, manual]
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: 'Upcoming Changelog'
    secrets: [ISSUE_TOKEN]
    image: docker.io/thegeeklab/git-sv:1.0.5
    commands: |
      apk add -q --no-cache curl jq
      export RELEASE_NOTES=$(git sv rn)
      export ISSUE_NUMBER=$(curl -s "${CI_FORGE_URL}/api/v1/repos/${CI_REPO}/issues?state=open&q=Changelog%20for%20next%20version" | jq '.[].number')

      if [ -z "$ISSUE_NUMBER" ]; then
        curl -s -X POST "${CI_FORGE_URL}/api/v1/repos/${CI_REPO}/issues?token=$ISSUE_TOKEN" -H 'Content-Type: application/json' -d "{\"title\":\"Changelog for next version\", \"body\":\"$RELEASE_NOTES\" }"
      else
        curl -s -X PATCH "${CI_FORGE_URL}/api/v1/repos/${CI_REPO}/issues/$ISSUE_NUMBER?token=$ISSUE_TOKEN" -H 'Content-Type: application/json' -d "{\"title\":\"Changelog for next version\", \"body\":\"$RELEASE_NOTES\" }"
      fi
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 300Mi
            cpu: 1000m
```
